# Generated by Django 5.2.8 on 2025-11-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0003_evidenciaresolucion_resolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_configuracion', models.CharField(max_length=20, unique=True, verbose_name='Código de Configuración')),
                ('recibir_email', models.BooleanField(default=True, verbose_name='Recibir Email')),
                ('recibir_sms', models.BooleanField(default=False, verbose_name='Recibir SMS')),
                ('recibir_push', models.BooleanField(default=True, verbose_name='Recibir Push')),
                ('frecuencia_resumen', models.CharField(choices=[('Inmediato', 'Inmediato'), ('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Ninguno', 'Ninguno')], default='Diario', max_length=20, verbose_name='Frecuencia de Resumen')),
                ('horario_preferido', models.CharField(blank=True, max_length=50, verbose_name='Horario Preferido')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificación',
                'db_table': 'configuracion_notificacion',
            },
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_plantilla', models.CharField(max_length=20, unique=True, verbose_name='Código de Plantilla')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo_evento', models.CharField(choices=[('Registro', 'Registro'), ('Actualización', 'Actualización'), ('Asignación', 'Asignación'), ('Resolución', 'Resolución'), ('Rechazo', 'Rechazo'), ('Comentario', 'Comentario')], max_length=50, verbose_name='Tipo de Evento')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('cuerpo_mensaje', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('variables', models.TextField(blank=True, help_text='Variables disponibles en formato JSON', verbose_name='Variables')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Está Activa')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'db_table': 'plantilla_notificacion',
                'indexes': [models.Index(fields=['tipo_evento'], name='idx_plantilla_tipo_evento'), models.Index(fields=['esta_activa'], name='idx_plantilla_activa')],
            },
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id_comunicacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_comunicacion', models.CharField(max_length=20, unique=True, verbose_name='Código de Comunicación')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('tipo_remitente', models.CharField(choices=[('Ciudadano', 'Ciudadano'), ('Personal', 'Personal'), ('Sistema', 'Sistema')], max_length=20, verbose_name='Tipo de Remitente')),
                ('es_leido', models.BooleanField(default=False, verbose_name='Es Leído')),
                ('requiere_respuesta', models.BooleanField(default=False, verbose_name='Requiere Respuesta')),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='denuncias.denuncia', verbose_name='Denuncia')),
                ('id_usuario_remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Remitente')),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'db_table': 'comunicacion',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['id_denuncia'], name='idx_comunicacion_denuncia'), models.Index(fields=['fecha_envio'], name='idx_comunicacion_fecha'), models.Index(fields=['es_leido'], name='idx_comunicacion_leido')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_notificacion', models.CharField(max_length=20, unique=True, verbose_name='Código de Notificación')),
                ('tipo_notificacion', models.CharField(max_length=50, verbose_name='Tipo de Notificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('canal_envio', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push'), ('Interno', 'Interno')], max_length=20, verbose_name='Canal de Envío')),
                ('estado_envio', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Fallido', 'Fallido'), ('Leído', 'Leído')], default='Pendiente', max_length=20, verbose_name='Estado de Envío')),
                ('mensaje_personalizado', models.TextField(verbose_name='Mensaje Personalizado')),
                ('intento_envio', models.IntegerField(default=1, verbose_name='Intento de Envío')),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='denuncias.denuncia', verbose_name='Denuncia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('id_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notificaciones.plantillanotificacion', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['id_usuario'], name='idx_notificacion_usuario'), models.Index(fields=['estado_envio'], name='idx_notificacion_estado'), models.Index(fields=['fecha_creacion'], name='idx_notificacion_fecha')],
            },
        ),
    ]
