# Generated by Django 5.2.8 on 2025-11-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantillanotificacion',
            table='plantillanotificacion',
        ),
    ]
