# Generated by Django 5.2.8 on 2025-11-16 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_plantillanotificacion_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionnotificacion',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_notificacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
