# Generated by Django 5.2.8 on 2025-11-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_configuracionnotificacion_id_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracionnotificacion',
            table='configuracionnotificacion',
        ),
    ]
