# Generated by Django 5.2.8 on 2025-11-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id_dashboard', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_dashboard', models.CharField(max_length=20, unique=True, verbose_name='Código de Dashboard')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_dashboard', models.CharField(choices=[('Ejecutivo', 'Ejecutivo'), ('Operativo', 'Operativo'), ('Ciudadano', 'Ciudadano'), ('Analítico', 'Analítico')], max_length=50, verbose_name='Tipo de Dashboard')),
                ('frecuencia_actualizacion', models.CharField(choices=[('Tiempo real', 'Tiempo real'), ('Diario', 'Diario'), ('Semanal', 'Semanal')], max_length=20, verbose_name='Frecuencia de Actualización')),
                ('es_publico', models.BooleanField(default=False, verbose_name='Es Público')),
                ('orden_visualizacion', models.IntegerField(blank=True, null=True, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'dashboard',
                'ordering': ['orden_visualizacion', 'nombre'],
                'indexes': [models.Index(fields=['tipo_dashboard'], name='idx_dashboard_tipo'), models.Index(fields=['es_publico'], name='idx_dashboard_publico')],
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_estadistica', models.CharField(max_length=20, unique=True, verbose_name='Código de Estadística')),
                ('tipo_metrica', models.CharField(max_length=50, verbose_name='Tipo de Métrica')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('periodo', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Período')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('zona', models.CharField(blank=True, max_length=100, verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'db_table': 'estadistica',
                'ordering': ['-fecha_calculo'],
                'indexes': [models.Index(fields=['tipo_metrica'], name='idx_estadistica_tipo_metrica'), models.Index(fields=['periodo'], name='idx_estadistica_periodo'), models.Index(fields=['fecha_calculo'], name='idx_estadistica_fecha'), models.Index(fields=['categoria'], name='idx_estadistica_categoria')],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_indicador', models.CharField(max_length=20, unique=True, verbose_name='Código de Indicador')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('formula', models.CharField(max_length=500, verbose_name='Fórmula')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Actual')),
                ('frecuencia_actualizacion', models.CharField(choices=[('Tiempo real', 'Tiempo real'), ('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual')], max_length=20, verbose_name='Frecuencia de Actualización')),
                ('tipo_visualizacion', models.CharField(choices=[('Gauge', 'Gauge'), ('LineChart', 'LineChart'), ('BarChart', 'BarChart'), ('PieChart', 'PieChart'), ('Number', 'Number')], max_length=20, verbose_name='Tipo de Visualización')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'db_table': 'indicador',
                'indexes': [models.Index(fields=['frecuencia_actualizacion'], name='idx_indicador_frecuencia')],
            },
        ),
        migrations.CreateModel(
            name='TendenciaGeografica',
            fields=[
                ('id_tendencia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_tendencia', models.CharField(max_length=20, unique=True, verbose_name='Código de Tendencia')),
                ('zona', models.CharField(max_length=100, verbose_name='Zona')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('cantidad_denuncias', models.IntegerField(verbose_name='Cantidad de Denuncias')),
                ('categoria_mas_frecuente', models.CharField(max_length=100, verbose_name='Categoría Más Frecuente')),
                ('tasa_resolucion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Resolución (%)')),
                ('tiempo_promedio_atencion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiempo Promedio de Atención')),
                ('periodo_analisis', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Período de Análisis')),
                ('nivel_criticidad', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=20, verbose_name='Nivel de Criticidad')),
            ],
            options={
                'verbose_name': 'Tendencia Geográfica',
                'verbose_name_plural': 'Tendencias Geográficas',
                'db_table': 'tendencia_geografica',
                'indexes': [models.Index(fields=['zona'], name='idx_tendencia_zona'), models.Index(fields=['distrito'], name='idx_tendencia_distrito'), models.Index(fields=['periodo_analisis'], name='idx_tendencia_periodo')],
            },
        ),
        migrations.CreateModel(
            name='DashboardIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden')),
                ('tipo_visualizacion', models.CharField(choices=[('Gauge', 'Gauge'), ('LineChart', 'LineChart'), ('BarChart', 'BarChart'), ('PieChart', 'PieChart'), ('Number', 'Number')], max_length=20, verbose_name='Tipo de Visualización')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('id_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_asignados', to='reportes.dashboard', verbose_name='Dashboard')),
                ('id_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards_asignados', to='reportes.indicador', verbose_name='Indicador')),
            ],
            options={
                'verbose_name': 'Dashboard Indicador',
                'verbose_name_plural': 'Dashboard Indicadores',
                'db_table': 'dashboard_indicador',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['id_dashboard'], name='idx_dash_ind_dash'), models.Index(fields=['id_indicador'], name='idx_dash_ind_indicador')],
                'unique_together': {('id_dashboard', 'id_indicador')},
            },
        ),
        migrations.CreateModel(
            name='RankingDesempeno',
            fields=[
                ('id_ranking', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ranking', models.CharField(max_length=20, unique=True, verbose_name='Código de Ranking')),
                ('periodo_evaluacion', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Período de Evaluación')),
                ('posicion', models.IntegerField(verbose_name='Posición')),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje Total')),
                ('denuncias_atendidas', models.IntegerField(verbose_name='Denuncias Atendidas')),
                ('tasa_resolucion_area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Resolución del Área (%)')),
                ('tiempo_promedio_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiempo Promedio del Área')),
                ('calificacion_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Calificación Promedio')),
                ('id_area_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankings', to='categorias.arearesponsable', verbose_name='Área Responsable')),
            ],
            options={
                'verbose_name': 'Ranking de Desempeño',
                'verbose_name_plural': 'Rankings de Desempeño',
                'db_table': 'ranking_desempeno',
                'ordering': ['posicion'],
                'indexes': [models.Index(fields=['periodo_evaluacion'], name='idx_ranking_periodo')],
                'unique_together': {('id_area_responsable', 'periodo_evaluacion')},
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_reporte', models.CharField(max_length=20, unique=True, verbose_name='Código de Reporte')),
                ('tipo_reporte', models.CharField(choices=[('Ejecutivo', 'Ejecutivo'), ('Operativo', 'Operativo'), ('Estadístico', 'Estadístico'), ('Auditoria', 'Auditoria')], max_length=50, verbose_name='Tipo de Reporte')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('formato_exportacion', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], max_length=10, verbose_name='Formato de Exportación')),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Ruta del Archivo')),
                ('es_publico', models.BooleanField(default=False, verbose_name='Es Público')),
                ('id_usuario_generador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Generador')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['tipo_reporte'], name='idx_reporte_tipo'), models.Index(fields=['fecha_generacion'], name='idx_reporte_fecha')],
            },
        ),
    ]
