# Generated by Django 5.2.8 on 2025-11-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboardindicador',
            table='DashboardIndicador',
        ),
        migrations.AlterModelTable(
            name='rankingdesempeno',
            table='RankingDesempeno',
        ),
        migrations.AlterModelTable(
            name='tendenciageografica',
            table='TendenciaGeografica',
        ),
    ]
