# Generated by Django 5.2.8 on 2025-11-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_dashboardindicador_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboardindicador',
            table='dashboardindicador',
        ),
        migrations.AlterModelTable(
            name='rankingdesempeno',
            table='rankingdesempeno',
        ),
        migrations.AlterModelTable(
            name='tendenciageografica',
            table='tendenciageografica',
        ),
    ]
