# Generated by Django 5.2.8 on 2025-11-16 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_dashboardindicador_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardindicador',
            name='id_dashboard',
            field=models.ForeignKey(db_column='id_dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_asignados', to='reportes.dashboard', verbose_name='Dashboard'),
        ),
        migrations.AlterField(
            model_name='dashboardindicador',
            name='id_indicador',
            field=models.ForeignKey(db_column='id_indicador', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards_asignados', to='reportes.indicador', verbose_name='Indicador'),
        ),
    ]
