# Generated by Django 5.2.8 on 2025-12-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_set_dashboardindicador_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='estado_generacion',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('En progreso', 'En progreso'), ('Completado', 'Completado'), ('Fallido', 'Fallido')], default='Borrador', max_length=20, verbose_name='Estado de Generación'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='parametros_configuracion',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parámetros de Configuración'),
        ),
    ]
