# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('ciudadanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ubicacion', models.CharField(max_length=20, unique=True, verbose_name='Código de Ubicación')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('referencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_denuncia', models.CharField(max_length=20, unique=True, verbose_name='Código de Denuncia')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.CharField(choices=[('Registrado', 'Registrado'), ('En revisión', 'En revisión'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Resuelta', 'Resuelta'), ('Rechazada', 'Rechazada'), ('Cerrada', 'Cerrada')], default='Registrado', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=20, verbose_name='Prioridad')),
                ('es_anonima', models.BooleanField(default=False, verbose_name='Es Anónima')),
                ('numero_seguimiento', models.CharField(max_length=20, unique=True, verbose_name='Número de Seguimiento')),
                ('requiere_validacion', models.BooleanField(default=True, verbose_name='Requiere Validación')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='categorias.categoria', verbose_name='Categoría')),
                ('id_ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='ciudadanos.ciudadano', verbose_name='Ciudadano')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'db_table': 'denuncia',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_evidencia', models.CharField(max_length=20, unique=True, verbose_name='Código de Evidencia')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_almacenamiento', models.CharField(max_length=500, unique=True, verbose_name='Ruta de Almacenamiento')),
                ('tipo_archivo', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/gif', 'GIF'), ('video/mp4', 'MP4'), ('application/pdf', 'PDF')], max_length=100, verbose_name='Tipo de Archivo')),
                ('tamaño_bytes', models.BigIntegerField(verbose_name='Tamaño en Bytes')),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Carga')),
                ('hash_archivo', models.CharField(max_length=64, unique=True, verbose_name='Hash del Archivo (SHA-256)')),
                ('esta_escaneado', models.BooleanField(default=False, verbose_name='Está Escaneado')),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='denuncias.denuncia', verbose_name='Denuncia')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencia',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_seguimiento', models.CharField(max_length=20, unique=True, verbose_name='Código de Seguimiento')),
                ('estado_anterior', models.CharField(blank=True, choices=[('Registrado', 'Registrado'), ('En revisión', 'En revisión'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Resuelta', 'Resuelta'), ('Rechazada', 'Rechazada'), ('Cerrada', 'Cerrada')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('Registrado', 'Registrado'), ('En revisión', 'En revisión'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Resuelta', 'Resuelta'), ('Rechazada', 'Rechazada'), ('Cerrada', 'Cerrada')], max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('es_visible', models.BooleanField(default=True, verbose_name='Es Visible para el Ciudadano')),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='denuncias.denuncia', verbose_name='Denuncia')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'db_table': 'seguimiento',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
