# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denuncias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['distrito'], name='idx_ubicacion_distrito'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['latitud', 'longitud'], name='idx_ubicacion_coordenadas'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='id_ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='denuncias.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['id_denuncia'], name='idx_evidencia_denuncia'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['tipo_archivo'], name='idx_evidencia_tipo'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['id_denuncia'], name='idx_seguimiento_denuncia'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['fecha_hora'], name='idx_seguimiento_fecha'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['estado'], name='idx_denuncia_estado'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['prioridad'], name='idx_denuncia_prioridad'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['fecha_registro'], name='idx_denuncia_fecha_registro'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['id_ciudadano'], name='idx_denuncia_ciudadano'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['id_categoria'], name='idx_denuncia_categoria'),
        ),
    ]
