# Generated by Django 5.2.8 on 2025-11-16 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaResolucion',
            fields=[
                ('id_evidencia_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_almacenamiento', models.CharField(max_length=500, unique=True, verbose_name='Ruta de Almacenamiento')),
                ('tipo_archivo', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('application/pdf', 'PDF')], max_length=100, verbose_name='Tipo de Archivo')),
                ('tamaño_bytes', models.BigIntegerField(verbose_name='Tamaño en Bytes')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('hash_archivo', models.CharField(max_length=64, unique=True, verbose_name='Hash del Archivo (SHA-256)')),
            ],
            options={
                'verbose_name': 'Evidencia de Resolución',
                'verbose_name_plural': 'Evidencias de Resolución',
                'db_table': 'evidencia_resolucion',
            },
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_resolucion', models.CharField(max_length=20, unique=True, verbose_name='Código de Resolución')),
                ('fecha_resolucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Resolución')),
                ('tipo_resolucion', models.CharField(choices=[('Resuelta', 'Resuelta'), ('Rechazada', 'Rechazada'), ('Duplicada', 'Duplicada'), ('No procede', 'No procede')], max_length=20, verbose_name='Tipo de Resolución')),
                ('descripcion_resolucion', models.TextField(verbose_name='Descripción de la Resolución')),
                ('tiempo_total_horas', models.IntegerField(verbose_name='Tiempo Total en Horas')),
                ('calificacion_ciudadano', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación del Ciudadano (1-5)')),
                ('comentario_ciudadano', models.TextField(blank=True, null=True, verbose_name='Comentario del Ciudadano')),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
                'db_table': 'resolucion',
            },
        ),
    ]
