# Generated by Django 5.2.8 on 2025-11-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_evidenciaresolucion_resolucion'),
        ('personal', '0003_asignacion_personaltelefono_tramitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciaresolucion',
            name='id_tramitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_resolucion', to='personal.tramitacion', verbose_name='Tramitación'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='id_tramitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='personal.tramitacion', verbose_name='Tramitación'),
        ),
        migrations.AddIndex(
            model_name='evidenciaresolucion',
            index=models.Index(fields=['id_tramitacion'], name='idx_ev_res_tramitacion'),
        ),
        migrations.AddIndex(
            model_name='resolucion',
            index=models.Index(fields=['tipo_resolucion'], name='idx_resolucion_tipo'),
        ),
        migrations.AddIndex(
            model_name='resolucion',
            index=models.Index(fields=['fecha_resolucion'], name='idx_resolucion_fecha'),
        ),
    ]
