# Generated by Django 5.2.8 on 2025-11-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_evidenciaresolucion_id_tramitacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evidenciaresolucion',
            table='EvidenciaResolucion',
        ),
    ]
