# Generated by Django 5.2.8 on 2025-11-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_alter_evidenciaresolucion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evidenciaresolucion',
            table='evidenciaresolucion',
        ),
    ]
