# Generated by Django 5.2.8 on 2025-11-16 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_alter_arearesponsable_id_jefe_area'),
        ('ciudadanos', '0005_set_defaults_ciudadano'),
        ('denuncias', '0006_alter_evidenciaresolucion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='categorias.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_ciudadano',
            field=models.ForeignKey(blank=True, db_column='id_ciudadano', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='ciudadanos.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_ubicacion',
            field=models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.PROTECT, related_name='denuncias', to='denuncias.ubicacion', verbose_name='Ubicación'),
        ),
    ]
