# Generated by Django 5.2.8 on 2025-11-16 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0011_set_denuncia_requiere_validacion_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='id_denuncia',
            field=models.ForeignKey(db_column='id_denuncia', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='denuncias.denuncia', verbose_name='Denuncia'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
