# Generated by Django 5.2.8 on 2025-11-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0014_set_seguimiento_es_visible_default'),
        ('personal', '0011_alter_tramitacion_id_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolucion',
            name='id_tramitacion',
            field=models.ForeignKey(db_column='id_tramitacion', on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='personal.tramitacion', verbose_name='Tramitación'),
        ),
    ]
