# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaResponsable',
            fields=[
                ('id_area_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_area', models.CharField(max_length=20, unique=True, verbose_name='Código de Área')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('capacidad_maxima', models.IntegerField(default=50, verbose_name='Capacidad Máxima')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
            ],
            options={
                'verbose_name': 'Área Responsable',
                'verbose_name_plural': 'Áreas Responsables',
                'db_table': 'area_responsable',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_categoria', models.CharField(max_length=20, unique=True, verbose_name='Código de Categoría')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe ser un código hexadecimal válido (ej: #FF5733)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
                ('tiempo_respuesta_promedio', models.IntegerField(blank=True, null=True, verbose_name='Tiempo Respuesta Promedio (horas)')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
    ]
