# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arearesponsable',
            name='id_jefe_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to='personal.personalmunicipal', verbose_name='Jefe de Área'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_area_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='categorias.arearesponsable', verbose_name='Área Responsable'),
        ),
        migrations.AddIndex(
            model_name='arearesponsable',
            index=models.Index(fields=['nombre'], name='idx_area_nombre'),
        ),
        migrations.AddIndex(
            model_name='arearesponsable',
            index=models.Index(fields=['esta_activo'], name='idx_area_activo'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['esta_activo'], name='idx_categoria_activo'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['id_area_responsable'], name='idx_categoria_area'),
        ),
    ]
