# Generated by Django 5.2.8 on 2025-11-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arearesponsable',
            table='arearesponsable',
        ),
    ]
