# Generated by Django 5.2.8 on 2025-11-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_fix_categoria_foreign_key'),
        ('personal', '0007_set_estado_laboral_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arearesponsable',
            name='id_jefe_area',
            field=models.ForeignKey(blank=True, db_column='id_jefe_area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to='personal.personalmunicipal', verbose_name='Jefe de Área'),
        ),
    ]
