# Generated by Django 5.2.8 on 2025-12-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_alter_arearesponsable_id_jefe_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_area_responsable',
            field=models.ForeignKey(db_column='id_area_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='categorias.arearesponsable', verbose_name='Área Responsable'),
        ),
    ]
