# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_usuario', models.CharField(max_length=20, unique=True, verbose_name='Código de Usuario')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('estado_cuenta', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado')], default='Activo', max_length=20, verbose_name='Estado de Cuenta')),
                ('intentos_login', models.IntegerField(default=0, verbose_name='Intentos de Login Fallidos')),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Bloqueo')),
                ('requiere_mfa', models.BooleanField(default=False, verbose_name='Requiere Autenticación Multifactor')),
                ('token_mfa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token MFA')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'indexes': [models.Index(fields=['estado_cuenta'], name='idx_usuario_estado'), models.Index(fields=['ultimo_acceso'], name='idx_usuario_ultimo_acceso')],
            },
        ),
    ]
