# Generated by Django 5.2.8 on 2025-11-16 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_permiso', models.CharField(max_length=20, unique=True, verbose_name='Código de Permiso')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Permiso')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('accion', models.CharField(choices=[('Crear', 'Crear'), ('Leer', 'Leer'), ('Actualizar', 'Actualizar'), ('Eliminar', 'Eliminar'), ('Ejecutar', 'Ejecutar')], max_length=50, verbose_name='Acción')),
                ('recurso', models.CharField(max_length=50, verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
                'indexes': [models.Index(fields=['modulo'], name='idx_permiso_modulo'), models.Index(fields=['accion'], name='idx_permiso_accion')],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_rol', models.CharField(max_length=20, unique=True, verbose_name='Código de Rol')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('nivel', models.PositiveIntegerField(verbose_name='Nivel del Rol')),
                ('es_sistema', models.BooleanField(default=True, verbose_name='Es Rol de Sistema')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'indexes': [models.Index(fields=['esta_activo'], name='idx_rol_activo'), models.Index(fields=['nivel'], name='idx_rol_nivel')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_log', models.CharField(max_length=20, unique=True, verbose_name='Código de Log')),
                ('tipo_accion', models.CharField(max_length=50, verbose_name='Tipo de Acción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('entidad', models.CharField(max_length=50, verbose_name='Entidad')),
                ('entidad_id', models.CharField(max_length=36, verbose_name='ID de Entidad')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('direccion_ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('datos_antes', models.TextField(blank=True, verbose_name='Datos Antes')),
                ('datos_despues', models.TextField(blank=True, verbose_name='Datos Después')),
                ('resultado', models.CharField(choices=[('Éxito', 'Éxito'), ('Error', 'Error'), ('Parcial', 'Parcial')], max_length=20, verbose_name='Resultado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'log_auditoria',
                'indexes': [models.Index(fields=['fecha_hora'], name='idx_log_fecha'), models.Index(fields=['modulo'], name='idx_log_modulo'), models.Index(fields=['id_usuario'], name='idx_log_usuario'), models.Index(fields=['resultado'], name='idx_log_resultado')],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permiso', verbose_name='Permiso')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol Permiso',
                'verbose_name_plural': 'Roles Permisos',
                'db_table': 'rol_permiso',
                'indexes': [models.Index(fields=['id_rol'], name='idx_rol_permiso_rol'), models.Index(fields=['id_permiso'], name='idx_rol_permiso_permiso')],
                'unique_together': {('id_rol', 'id_permiso')},
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_sesion', models.CharField(max_length=20, unique=True, verbose_name='Código de Sesión')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Token de Sesión')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('direccion_ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(max_length=500, verbose_name='User Agent')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Está Activa')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sesion',
                'indexes': [models.Index(fields=['token'], name='idx_sesion_token'), models.Index(fields=['esta_activa'], name='idx_sesion_activa'), models.Index(fields=['id_usuario'], name='idx_sesion_usuario')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario Rol',
                'verbose_name_plural': 'Usuarios Roles',
                'db_table': 'usuario_rol',
                'indexes': [models.Index(fields=['id_usuario'], name='idx_usuario_rol_usuario'), models.Index(fields=['id_rol'], name='idx_usuario_rol_rol')],
                'unique_together': {('id_usuario', 'id_rol')},
            },
        ),
    ]
