# Generated by Django 5.2.8 on 2025-11-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permiso_rol_logauditoria_rolpermiso_sesion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logauditoria',
            table='LogAuditoria',
        ),
        migrations.AlterModelTable(
            name='rolpermiso',
            table='RolPermiso',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='UsuarioRol',
        ),
    ]
