# Generated by Django 5.2.8 on 2025-11-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_logauditoria_table_alter_rolpermiso_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logauditoria',
            table='logauditoria',
        ),
        migrations.AlterModelTable(
            name='rolpermiso',
            table='rolpermiso',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='usuariorol',
        ),
    ]
