# Generated by Django 5.2.8 on 2025-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_logauditoria_table_alter_rolpermiso_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='resultado',
            field=models.CharField(choices=[('Exitoso', 'Exitoso'), ('Fallido', 'Fallido'), ('Advertencia', 'Advertencia')], max_length=20, verbose_name='Resultado'),
        ),
    ]
