# Generated by Django 5.2.8 on 2025-11-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_add_password_hash_to_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password_hash',
        ),
    ]
