# Generated by Django 5.2.8 on 2025-11-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuario_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash de Contraseña'),
        ),
    ]
