# Generated by Django 5.2.8 on 2025-11-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuario_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
