# Generated by Django 5.2.8 on 2025-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_usuario_is_active_remove_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='logauditoria',
            name='idx_log_resultado',
        ),
        migrations.RemoveIndex(
            model_name='sesion',
            name='idx_sesion_token',
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['tipo_accion'], name='idx_log_tipo_accion'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['entidad', 'entidad_id'], name='idx_log_entidad'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['fecha_expiracion'], name='idx_sesion_expiracion'),
        ),
    ]
