# Generated by Django 5.2.8 on 2025-11-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_logauditoria_idx_log_resultado_and_more'),
    ]

    operations = [
    ]
