# Generated by Django 5.2.8 on 2025-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20251116_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password_hash',
            field=models.CharField(default='', max_length=255, verbose_name='Hash de Contraseña'),
        ),
    ]
