# Generated by Django 5.2.8 on 2025-11-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_usuario_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
