# Generated by Django 5.2.8 on 2025-11-16 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_set_db_defaults'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='rolpermiso',
                    name='id_permiso',
                    field=models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='usuarios.permiso', verbose_name='Permiso'),
                ),
                migrations.AlterField(
                    model_name='rolpermiso',
                    name='id_rol',
                    field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol'),
                ),
                migrations.AlterField(
                    model_name='usuariorol',
                    name='id_rol',
                    field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol', verbose_name='Rol'),
                ),
                migrations.AlterField(
                    model_name='usuariorol',
                    name='id_usuario',
                    field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
                ),
            ],
        ),
    ]
