# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id_ciudadano', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_ciudadano', models.CharField(max_length=20, unique=True, verbose_name='Código de Ciudadano')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos numéricos', regex='^\\d{8}$')], verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_emision_dni', models.DateField(verbose_name='Fecha de Emisión del DNI')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('es_anonimo', models.BooleanField(default=False, verbose_name='Es Anónimo')),
                ('estado_cuenta', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20, verbose_name='Estado de Cuenta')),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
                'db_table': 'ciudadano',
            },
        ),
        migrations.CreateModel(
            name='CiudadanoTelefono',
            fields=[
                ('id_ciudadano_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 20 caracteres y solo puede contener números, +, -, espacios y paréntesis', regex='^[0-9+\\-\\s()]{7,20}$')], verbose_name='Teléfono')),
                ('es_principal', models.BooleanField(default=True, verbose_name='Es Principal')),
            ],
            options={
                'verbose_name': 'Teléfono de Ciudadano',
                'verbose_name_plural': 'Teléfonos de Ciudadanos',
                'db_table': 'ciudadano_telefono',
            },
        ),
    ]
