# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudadanos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='id_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudadano', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='ciudadanotelefono',
            name='id_ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='ciudadanos.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['dni'], name='idx_ciudadano_dni'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['estado_cuenta'], name='idx_ciudadano_estado'),
        ),
        migrations.AddIndex(
            model_name='ciudadanotelefono',
            index=models.Index(fields=['id_ciudadano'], name='idx_ciud_tel_ciudadano'),
        ),
        migrations.AlterUniqueTogether(
            name='ciudadanotelefono',
            unique_together={('id_ciudadano', 'telefono')},
        ),
    ]
