# Generated by Django 5.2.8 on 2025-11-16 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0003_alter_ciudadanotelefono_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudadano', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='ciudadanotelefono',
            name='id_ciudadano',
            field=models.ForeignKey(db_column='id_ciudadano', on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='ciudadanos.ciudadano', verbose_name='Ciudadano'),
        ),
    ]
