# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMunicipal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_personal', models.CharField(max_length=20, unique=True, verbose_name='Código de Personal')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 dígitos numéricos', regex='^\\d{8}$')], verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('estado_laboral', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vacaciones', 'Vacaciones'), ('Licencia', 'Licencia'), ('Desvinculado', 'Desvinculado')], default='Activo', max_length=20, verbose_name='Estado Laboral')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('id_area_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='categorias.arearesponsable', verbose_name='Área Responsable')),
            ],
            options={
                'verbose_name': 'Personal Municipal',
                'verbose_name_plural': 'Personal Municipal',
                'db_table': 'personal_municipal',
            },
        ),
    ]
