# Generated by Django 5.2.8 on 2025-11-13 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmunicipal',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='personalmunicipal',
            index=models.Index(fields=['id_area_responsable'], name='idx_personal_area'),
        ),
        migrations.AddIndex(
            model_name='personalmunicipal',
            index=models.Index(fields=['estado_laboral'], name='idx_personal_estado'),
        ),
    ]
