# Generated by Django 5.2.8 on 2025-11-16 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_evidenciaresolucion_resolucion'),
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_asignacion', models.CharField(max_length=20, unique=True, verbose_name='Código de Asignación')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('motivo_asignacion', models.TextField(blank=True, max_length=500, verbose_name='Motivo de Asignación')),
                ('es_activa', models.BooleanField(default=True, verbose_name='Está Activa')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('id_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='denuncias.denuncia', verbose_name='Denuncia')),
                ('id_personal_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to='personal.personalmunicipal', verbose_name='Personal Asignado')),
                ('id_personal_asignador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_realizadas', to='personal.personalmunicipal', verbose_name='Personal Asignador')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'db_table': 'asignacion',
            },
        ),
        migrations.CreateModel(
            name='PersonalTelefono',
            fields=[
                ('id_personal_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 7 y 20 caracteres y solo puede contener números, +, -, espacios y paréntesis', regex='^[0-9+\\-\\s()]{7,20}$')], verbose_name='Teléfono')),
                ('es_principal', models.BooleanField(default=True, verbose_name='Es Principal')),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='personal.personalmunicipal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Teléfono de Personal',
                'verbose_name_plural': 'Teléfonos de Personal',
                'db_table': 'personal_telefono',
            },
        ),
        migrations.CreateModel(
            name='Tramitacion',
            fields=[
                ('id_tramitacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_tramitacion', models.CharField(max_length=20, unique=True, verbose_name='Código de Tramitación')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('accion_realizada', models.TextField(verbose_name='Acción Realizada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Estimado')),
                ('estado_tramitacion', models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Suspendido', 'Suspendido'), ('Cancelado', 'Cancelado')], default='En proceso', max_length=20, verbose_name='Estado de Tramitación')),
                ('id_asignacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacion', to='personal.asignacion', verbose_name='Asignación')),
            ],
            options={
                'verbose_name': 'Tramitación',
                'verbose_name_plural': 'Tramitaciones',
                'db_table': 'tramitacion',
            },
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['id_denuncia'], name='idx_asignacion_denuncia'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['es_activa'], name='idx_asignacion_activa'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['id_personal_asignado'], name='idx_asignacion_personal'),
        ),
        migrations.AddIndex(
            model_name='personaltelefono',
            index=models.Index(fields=['id_personal'], name='idx_personal_telefono_personal'),
        ),
        migrations.AlterUniqueTogether(
            name='personaltelefono',
            unique_together={('id_personal', 'telefono')},
        ),
        migrations.AddIndex(
            model_name='tramitacion',
            index=models.Index(fields=['estado_tramitacion'], name='idx_tramitacion_estado'),
        ),
    ]
