# Generated by Django 5.2.8 on 2025-11-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_asignacion_personaltelefono_tramitacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personaltelefono',
            table='PersonalTelefono',
        ),
    ]
