# Generated by Django 5.2.8 on 2025-11-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_set_estado_laboral_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltelefono',
            name='id_personal',
            field=models.ForeignKey(db_column='id_personal', on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='personal.personalmunicipal', verbose_name='Personal'),
        ),
    ]
