# Generated by Django 5.2.8 on 2025-11-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0014_set_seguimiento_es_visible_default'),
        ('personal', '0008_alter_personaltelefono_id_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='id_denuncia',
            field=models.ForeignKey(db_column='id_denuncia', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='denuncias.denuncia', verbose_name='Denuncia'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id_personal_asignado',
            field=models.ForeignKey(db_column='id_personal_asignado', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to='personal.personalmunicipal', verbose_name='Personal Asignado'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id_personal_asignador',
            field=models.ForeignKey(db_column='id_personal_asignador', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_realizadas', to='personal.personalmunicipal', verbose_name='Personal Asignador'),
        ),
    ]
