# Generated by Django 5.2.8 on 2025-11-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_set_asignacion_es_activa_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacion',
            name='id_asignacion',
            field=models.OneToOneField(db_column='id_asignacion', on_delete=django.db.models.deletion.PROTECT, related_name='tramitacion', to='personal.asignacion', verbose_name='Asignación'),
        ),
    ]
